from requests import Response

class XYZException(Exception):
    def __init__(self, res: Response, msg: str = None):
        self.res: Response = ...
        self.msg: str = ...
        self.exc_data: str = ...

class BadRequest(XYZException): ...
class InternalServerError(XYZException): ...
class NotFound(XYZException): ...
class RegistrationError(XYZException): ...
class ActivationError(XYZException): ...
class AuthorizationError(XYZException): ...
class PasswordRestoreError(XYZException): ...
class AccountDeletionError(XYZException): ...
class OutOfRateLimits(XYZException): ...
class NotAllowed(XYZException): ...
class InvalidToken(XYZException): ...
class NotInitialized(XYZException): ...
class NotAcceptable(XYZException): ...
class AlreadyExists(XYZException): ...